### ISSUE TITLE
the user login image is not proper

### ISSUE THREAD

**Issue by ChiragAgarwal7** [coding-blocks/dukaan-admin-frontend#31]
![Screenshot 2019-10-20 at 4 55 19 PM](https://user-images.githubusercontent.com/43092941/67159095-b377ed00-f35d-11e9-9c64-803d00fb5a39.png)

**Comment by parammittal16** [comment]
hi @ChiragAgarwal7 I want to do this can u tell me what and which image is to be changed?

**Comment by parthpandyappp** [comment]
I would like to contribute to this issue!

**Comment by parammittal16** [comment]
Hi @parthpandyappp happy to see your concern but I have submitted a PR for his one ou can find more issues [here](https://github.com/coding-blocks/dukaan-admin-frontend/issues). Cheers!
